Homework 26.1 completed
Borisko130/jv-shop-homework24 pull request #4
Opened 2020-09-09 18:02 UTC by Borisko130

2020-09-09 20:52 UTC, DariaPikul requested changes
Where is the method for deleting products from the cart?

2020-09-09 20:52 UTC, DariaPikul commented on src/main/java/com/internet/shop/controller/AddProductController.java
> +    private final ProductService productService
```suggestion
    private ProductService productService
```

2020-09-09 20:52 UTC, DariaPikul commented on src/main/java/com/internet/shop/controller/AddProductController.java
> +    private final ProductService productService
Let's fix that for every service object

2020-09-09 20:52 UTC, DariaPikul commented on src/main/java/com/internet/shop/controller/AddProductController.java
> +        String price = req.getParameter("price");
Let's check the received String's length 
We can't work with the empty ones

2020-09-09 20:52 UTC, DariaPikul commented on src/main/java/com/internet/shop/controller/AddUserController.java
> +        String passRep = req.getParameter("pass-repeat");
Same here

2020-09-09 20:52 UTC, DariaPikul commented on src/main/java/com/internet/shop/controller/ShowProductsController.java
> +        req.setAttribute("products", productList);
```suggestion
        List<Product> productList = productService.getAll();
        req.setAttribute("products", productList);
```

2020-09-09 20:52 UTC, DariaPikul commented on src/main/java/com/internet/shop/controller/ShowUsersController.java
> +        req.setAttribute("users", allUsers);
```suggestion
        List<User> allUsers = userService.getAll();
        req.setAttribute("users", allUsers);
```

2020-09-10 07:48 UTC, RomanDubovskyi commented on src/main/java/com/internet/shop/controller/AddToCartController.java
> +public class AddToCartController extends HttpServlet {
```suggestion
public class AddProductToCartController extends HttpServlet {
```

2020-09-10 07:48 UTC, RomanDubovskyi commented on src/main/java/com/internet/shop/controller/AddToCartController.java
> +    private static ShoppingCart shoppingCart;
why shoppingCart is static?

2020-09-10 07:48 UTC, RomanDubovskyi commented on src/main/java/com/internet/shop/controller/DeleteUserController.java
> +        Long id = Long.valueOf(userId);
let's delete here shoppingCart as well

2020-09-10 07:48 UTC, RomanDubovskyi commented on src/main/java/com/internet/shop/controller/InjectDataController.java
> +        User user2 = new User("NotBoris", "userito", "passito");
let's add them shoppingCarts as well

2020-09-10 07:48 UTC, RomanDubovskyi commented on src/main/java/com/internet/shop/controller/ShowCartController.java
> +        } catch (NoSuchElementException e) {
if you will get NoSuchElement here it doesn't mean cart is empty, it means cart doesn't exist, you shouldn't have try catch here

2020-09-10 07:48 UTC, RomanDubovskyi commented on src/main/java/com/internet/shop/controller/ShowProductsController.java
> +public class ShowProductsController extends HttpServlet {
```suggestion
public class GetAllProductsController extends HttpServlet {
```

2020-09-10 07:48 UTC, RomanDubovskyi commented on src/main/java/com/internet/shop/controller/ShowUsersController.java
> +public class ShowUsersController extends HttpServlet {
```suggestion
public class GetAllUsersController extends HttpServlet {
```

2020-09-10 07:48 UTC, RomanDubovskyi commented on src/main/webapp/web.xml
> +        <url-pattern>/shopping-carts/products/</url-pattern>
```suggestion
        <url-pattern>/shopping-cart/products/</url-pattern>
```

2020-09-10 07:48 UTC, RomanDubovskyi commented on src/main/webapp/web.xml
> +        <url-pattern>/shopping-carts/products/add</url-pattern>
```suggestion
        <url-pattern>/shopping-cart/products/add</url-pattern>
```

2020-09-10 07:48 UTC, RomanDubovskyi commented on src/main/webapp/web.xml
> +        <url-pattern>/users/all</url-pattern>
```suggestion
        <url-pattern>/users</url-pattern>
```

2020-09-10 10:55 UTC, RomanDubovskyi approved these changes

2020-09-10 10:55 UTC, RomanDubovskyi commented on src/main/java/com/internet/shop/controller/AddUserController.java
> +public class AddUserController extends HttpServlet {
```suggestion
public class RegisterUserController extends HttpServlet {
```
that's optional, but i think this way it would more clear

2020-09-10 10:57 UTC, merged